### PR TITLE
Allows to send email using AWS SES in To, CC & BCC fields

### LINKED ISSUE #63: how to send CC and TO in the same email
Enhancement Request
The current library only allows a person object to be created , Amazon SES allows to pass multiple email addresses separated by a comma, or it takes a string array and send it to multiple folks, 
Change would require to allows receivers to be either in TO or CC category.

### PR DESCRIPTION
**Pull request by amitmawkin**
- Supports passing of email address array as person objects for To, CC & BCC fields
- Add supports for corporate proxy if needed
- Works with IAM role and AWS Short token service generated in your aws config
- Unit test 100% coverage for the added code.
- Fixes #63 

ENV file format can be as below for newer fields
```
export TEMPLATE_DIRECTORY=examples/templates
export SENDER_EMAIL_ADDRESS=who@anyone.com
export AWS_PROFILE=<if you have any profile - this fields is optional>
export AWS_REGION=us-east-1
export HTTP_PROXY=http://localhost:8099
export HTTPS_PROXY=https://localhost:8099
export https_proxy=$HTTP_PROXY
export http_proxy=$HTTP_PROXY
export NO_PROXY=169.254.169.254
```

### CODE REVIEW

**Comment by amitmawkin** [comment]
Need to check why travis is failing tests when they are succeeding locally

**Comment by nelsonic** [comment]
@amitmawkin thanks for sending us this PR. 👍 
we will try to take a look at it tomorrow (_unless it's urgent for your work tonight...?_)

**Comment by amitmawkin** [comment]
@nelsonic thanks no urgency as i can always pack my local packages with the changes, I will spend some time tomorrow to check why travis tests are failing and local succeeds thanks again

**Comment by nelsonic** [comment]
@amitmawkin so... the _reason_ Travis-CI is failing is simple: the PR is coming from _outside_ our Org.
if you push your code to a branch within @dwyl we can help you debug the Travis-CI build.
(_BTW: based on the fact that you have added **good tests** for your contribution and prepared a **well-documented Pull Request** closely following the [**contributing guide**](https://github.com/dwyl/contributing), you have been granted **write access** to the repo_)

**Comment by amitmawkin** [comment]
@nelsonic this should be in good shape now, it is failing due to lack of .env file .  Also as .env file contains AWS profile , tokens etc and we are not suppose to check it in so not sure how to test it.
Please review.

**Comment by nelsonic** [comment]
@amitmawkin I have granted you _write_ access to dwyl. https://github.com/dwyl/sendemail/invitations
image
Please push your branch to `this` origin: git@github.com:dwyl/sendemail.git
and re-create the PR with the branch in the dwyl the org.
this will allow us to debut the CI build _with_ you. 👍

**Comment by nelsonic** [comment]
@amitmawkin we ❤️  your _enthusiasm_ and _really_ appreciate you wanting to contribute code! 🎉 
but ... [dwyl/contributing > #3-pr-ettiquete](https://github.com/dwyl/contributing/tree/0a26b4bdd0d85724ea8d0181e71e01087ae3ee69#3-pr-ettiquete) bullet point ***3*** ... `#NeverMergeYourOwnPullRequest` ... 
(_our apologies if this is unclear from the request above..._)

@iteles we need to _proliferate_ the `CONTRIBUTING.md` through _all_ @dwyl repos.
(_it's not @amitmawkin's "**fault**" that the PR contribution steps ("workflow") were not **clear**...
but this **cannot** happen again..._) 😞

**Comment by amitmawkin** [comment]
@nelsonic  my mistake, i was trying to push the branch upstream but ended up pushing to master, as soon as I realized it I reverted it back, I have pushed the branch now for build and review. Sorry for the confusion.

**Pull request merged**
